version: "3.7"

services:
  discount_postgres:
    image: postgres
    container_name: discount_postgres
    read_only: true
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=discountDb
    expose:
      - "54323"
    ports:
      - "54323:54323"
    tmpfs:
      - /tmp
      - /run
      - /run/postgresql
    volumes:
      - discount-volume:/var/lib/postgresql/data
    command: -p 54323

volumes:
  discount-volume:
